<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Admin\ProductCode;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductCodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'product' => '1001',
                'product_code' => 'Asia Gaming',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '100.0000',
            ],
            [
                'product' => '1001',
                'product_code' => 'Asia Gaming',
                'game_type' => 'Live Casino(2)',
                'currency_code' => 'MMK',
                'conversion_rate' => '100.0000',
            ],
            [
                'product' => '1002',
                'product_code' => 'Evolution Gaming',
                'game_type' => 'Live Casino(2)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
             [
                'product' => '1004',
                'product_code' => 'Big Gaming',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1000.0000',
            ],
             [
                'product' => '1004',
                'product_code' => 'Big Gaming',
                'game_type' => 'Live Casino(2)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1000.0000',
            ],
            [
                'product' => '1006',
                'product_code' => 'Pragmatic Play',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1006',
                'product_code' => 'Pragmatic Play',
                'game_type' => 'Live Casino(2)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],

            [
                'product' => '1007',
                'product_code' => 'PG Soft',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1009',
                'product_code' => 'CQ9',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1009',
                'product_code' => 'CQ9',
                'game_type' => 'Fishing (8)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],

            [
                'product' => '1012',
                'product_code' => 'SBO',
                'game_type' => 'Sport Book(3)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1013',
                'product_code' => 'Joker',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1013',
                'product_code' => 'Joker',
                'game_type' => 'Fishing(8)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1016',
                'product_code' => 'YEE Bet',
                'game_type' => 'Live Casino(2)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1022',
                'product_code' => 'Sexy Gaming',
                'game_type' => 'Live Casino(2)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1023',
                'product_code' => 'Real Time Gaming	',
                'game_type' => 'Slot (1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1027',
                'product_code' => 'Yggdrasll',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1027',
                'product_code' => 'Yggdrasll',
                'game_type' => 'Live Casino(2)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1034',
                'product_code' => 'Spade Gaming',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1034',
                'product_code' => 'Spade Gaming',
                'game_type' => 'Fishing(8)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1035',
                'product_code' => 'Vivo Gaming',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1035',
                'product_code' => 'Vivo Gaming',
                'game_type' => 'Live Casino(2)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1038',
                'product_code' => 'King 855',
                'game_type' => 'Live Casino(2)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1041',
                'product_code' => 'Habanero',
                'game_type' => 'Slot (1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1050',
                'product_code' => 'PlayStar',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1050',
                'product_code' => 'PlayStar',
                'game_type' => 'Fishing(8)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1055',
                'product_code' => 'Mr Slotty',
                'game_type' => 'Slot (1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1056',
                'product_code' => 'TrueLab',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1058',
                'product_code' => 'BGaming',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1060',
                'product_code' => 'Wazdan',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1062',
                'product_code' => 'Fazi',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1063',
                'product_code' => 'Play Pearls',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1064',
                'product_code' => 'Net Game',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1065',
                'product_code' => 'Kiron',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1067',
                'product_code' => 'Red Rake',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1070',
                'product_code' => 'Boongo',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1077',
                'product_code' => 'Skywind',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1084',
                'product_code' => 'Advant Play',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1085',
                'product_code' => 'JDB',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '100.0000',
            ],
            [
                'product' => '1086',
                'product_code' => 'GENESIS',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1089',
                'product_code' => 'Simple Play',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1000.0000',
            ],
            [
                'product' => '1089',
                'product_code' => 'Simple Play',
                'game_type' => 'Fishing(8)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1000.0000',
            ],
            [
                'product' => '1091',
                'product_code' => 'JiLi',
                'game_type' => 'Slot (1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1097',
                'product_code' => 'Funta Gaming',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1098',
                'product_code' => 'Felix Gaming',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1100',
                'product_code' => 'SmartSoft',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1101',
                'product_code' => 'ZeusPlay',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1102',
                'product_code' => 'KA Gaming',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1104',
                'product_code' => 'SSports',
                'game_type' => 'Sport Book (3)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1109',
                'product_code' => 'Netent',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1110',
                'product_code' => 'Red Tiger',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1111',
                'product_code' => 'Gaming World',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1132',
                'product_code' => 'YesGetRich',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            [
                'product' => '1150',
                'product_code' => 'Live22SM',
                'game_type' => 'Slot(1)',
                'currency_code' => 'MMK',
                'conversion_rate' => '1.0000',
            ],
            
        ];

        ProductCode::insert($data);
    }
}
